### PR TITLE
Create sapin.c

### PR DESCRIPTION
**Pull request by moul**
```console
$ cc -o sapin sapin.c
$ ./sapin 5
                   *
                  ***
                 *****
                *******
                 *****
                *******
               *********
              ***********
             *************
              ***********
             *************
            ***************
           *****************
          *******************
         *********************
           *****************
          *******************
         *********************
        ***********************
       *************************
      ***************************
     *****************************
       *************************
      ***************************
     *****************************
    *******************************
   *********************************
  ***********************************
 *************************************
***************************************
                 |||||
                 |||||
                 |||||
                 |||||
                 |||||
```

Made by @moul and @korfuri

### CODE REVIEW

**Comment by MinhasKamal** [comment]
That was a wonderful piece of code! Thanks! :smiley: 

I have formatted the code a little. Hope you won't mind.

**Comment by MinhasKamal** [comment]
Could you please provide any explanation of how the code works?

**Comment by moul** [comment]
Thanks, sure, here are the steps to reproduce:

1. write a recursive `christmas tree generator`

```c
#include <stdlib.h>
#include <unistd.h>

#define C(B, E, S)  (1 + (E) * 2 + (B) * 4 + (((B) / 2) * 2) * (((B) + 1) / 2))

int	my_putchar(char c)
{
  return (write(1, &c, 1));
}

int	my_putline(int a, int b, int bmax, int size, char c)
{
  return (a < (C(size - 1, size + 3, size) - bmax - 1) / 2 ?
	  (my_putchar(' ') + my_putline(++a, b, bmax, size, c)) :
	  (b < bmax ? my_putchar(c) + my_putline(a, ++b, bmax, size, c) :
	   my_putchar('\n')));
}

int	sapin_rec(int b, int e, int s)
{
  return (b < s ? (e < b + 4 ? my_putline(0, 0, C(b, e, s), s, '*') +
		   sapin_rec(b, ++e, s) : sapin_rec(++b, 0, s)) :
	  e < s ? my_putline(0, 0, s | 1, s, '|') + sapin_rec(b, ++e, s) : 0);
}

int	sapin(int s)
{
  return (sapin_rec(0, 0, s));
}

int	main(int ac, char **av)
{
  if (ac > 1 && atoi(av[1]) >= 0)
    sapin(atoi(av[1]));
  return (EXIT_SUCCESS);
}
```

2. golf it

```c
#define C(B, E, S)  (1 + (E) * 2 + (B) * 4 + (((B) / 2) * 2) * (((B) + 1) / 2))

int	__(int a, int b, int d, int s, char c)
{
  return (a < (C(s - 1, s + 3, s) - d - 1) / 2 ?
	  (write(1, " ", 1) + __(++a, b, d, s, c)) :
	  (b < d ? write(1, &c, 1) + __(a, ++b, d, s, c) :
	   write(1, "\n", 1)));
}

int	_(int br, int e, int a, int b, int s)
{
  return (br < s ? (e < br + 4 ? __(0, 0, C(br, e, s), s, '*') +
		    _(br, ++e, 0, 0, s) : _(++br, 0, 0, 0, s)) :
	  e < s ? __(0, 0, s | 1, s, '|') + _(br, ++e, 0, 0, s) : 0);
}

int	main(int c, char **v)
{
  return (c > 1 && atoi(1[v]) >= 0 ? _(0, 0, 0, 0, atoi(1[v])) : 0);
}
```

3. golf it again

```c
#define C(B,E,S)(1+(E)*2+(B)*4+(((B)/2)*2)*(((B)+1)/2))
__(int $,int o,int O,int Q,char c){return $<(C(Q-1,Q+3,
Q)-O-1)/2?(write(1," ",1)+__(++$,o,O,Q,c)):(o<O?write(1
,&c,1)+__($,++o,O,Q,c):write(1,"\n",1));}_(int or,int e
,int $,int o,int Q){return or<Q?(e<or+4?__(0,0,C(or,e,Q
),Q,'*')+_(or,++e,0,0,Q):_(++or,0,0,0,Q)):e<Q?__(0,0,Q|
1,Q,'|')+_(or,++e,0,0,Q):0;}main(int c,char **v){return
c>1&&atoi(1[v])>=0?_(0,0,0,0,atoi(1[v])):0;}
```

4. stylize it

```c
#define C(B,E,S)(1+(E)*2+(B)*4+(((B)/2)*2)*(((B)+1)/2))

/*  Code by moul  */ __ /* (ugly) Art by Korfuri */

/* by */                     (
/* ko */                    int
/* rf */                   $,int
/* ur */                  o,int O
/* i& */                   , int
/* mo */                  Q ,char
/* ul */                 c){return
/* vi */                $<(C(Q-1,Q+
/* ve */               3,Q)-O-1)/2?(
/* le */                write(1," "
/* mo */               ,1)+__(++$,o,
/* uv */              O,Q,c )): (o<O?
/* em */             write(1,&c,1)+__(
/* en */            $,++o,O,Q,c):write(
/* td */           1,"\n",1));}_(int or,
/* es */             int e,int $,int o
/* as */            ,int Q){return or<Q
/* te */           ?(e<or+4?__(0,0,C(or,
/* ks */          e,Q),Q,42)+_(or,++e,0,0
/* di */         ,Q): _(++or,0,0,0,Q)):e<Q
/* ss */        ?__(0,0,Q|1,Q,'|')+_(or,++e
/* id */       ,0,0,Q):0;}main(int c,char**v
){return                   c>1&&
/* en */                   atoi(
/* ts */                   1[v])
/* <3 */                   >=0?_
/*/*             (2,0,0,8,astk(0[x])):c;}             /**/
/**/             (0,0,0,0,atoi(1[v])):0;}             //**
```

**Comment by Hunter313839** [comment]
ENG: In which programming language the code is written ???

**Comment by korfuri** [comment]
@Hunter313839  This is written in C. See @moul's comments above for ungolfed versions of the code that look more like regular C :)

**Pull request merged**
