### PR TITLE
Create backward.java

### PR DESCRIPTION
**Pull request by TheTrio**
This code prints Hello World!
Run it [here]( http://ideone.com/4heX2G)
Can't figure it out ? There is a StackOverflow question posted by me [here](http://stackoverflow.com/questions/43943699/why-does-this-code-written-backwards-print-hello-world)

### CODE REVIEW

**Comment by MinhasKamal** [comment]
Hello Shashwat,

Your code is really intriguing! I definitely want to add it to the collection.

But I could not compile the code in Eclipse or in [TutorialsPoint-CodingGround](https://www.tutorialspoint.com/codingground.htm) (it did compile in Ideone). Could you please help me in this?

Actually, I came up with a different version of your code-

Backward.java
--------------
    public class Backward{public static void main(String[]a‭‮){System.out.print(new char[]{'B','a','c','k','w','a','r','d','!'});}}

It runs in all places. What do you think about it?

Thanks :)

**Comment by TheTrio** [comment]
I guess the reason it didn't work in eclipse, is that it contains hidden unicode characters, and the IDEs try to parse them as well.

What works in yours may not work in mine. However, both display the same aspect, and thus, I have no objection with your code too.

Thanks

**Comment by MinhasKamal** [comment]
Good Day Shashwat,

I apologize, if you felt offended by my comment. I have no objection with your code, not even a little. Rather, I am interested in it. Your code is really wonderful.

I simply want to say that- the code you provided does not run on all platforms. So, if someone wants to run it, he/she may face difficulty. So, I took your code and made a tiny change. And now, it runs on all platforms (you may verify it). 

So, I was wondering- I will merge your pull request and then change the code a little. What do you think?

**Comment by TheTrio** [comment]
Haha, don't worry, I am not at all offended.I actually intended to type _no objection_, but that came out as _objection_ Go ahead, I am with you :)

**Pull request merged**
